dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "charlemaznable"
script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=CharLemAznable_bunny-client
after_success:
  - bash <(curl -s https://codecov.io/bash)
